spring:
  jpa:
    show-sql: false
    database-platform: com.mindata.blockchain.core.sqlite.config.SQLiteDialect
    generate-ddl: true
sqlite:
  dbName: a.db  #本地sqlite的名字
db:
  levelDB: true    #在部分Windows机器上rocksDB会报错dll找不到，那么就用levelDB来替代
  rocksDB: false
singleNode: false  #如果是单节点测试，改成true
version: 1
name: b5
appId: b5
managerUrl: http://172.17.0.3:8080/